version: "3.7"

services:
  socioformadorapi:
    image: mxdevelopers/socioformadorapi:0.5
    ports:
      - "8081:80"
    expose:
      - 80
      - 443
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=mysql
      - DBPORT=3306
      - DBNAME=SocioFormadorDB
      - DBUSER=root
      - DBPASSWORD=secret
  
  mysql:
    image: mysql:5.7
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./mysql5-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=SocioFormadorDB
