version: "3.7"

services:

  app:
    image: pablokbs/getting-started:v2
    ports:
      - "3000:3000"
    environment:
     MYSQL_HOST: mysql
     MYSQL_USER: root
     MYSQL_PASSWORD: secret
     MYSQL_DB: todos

  socioformadorapidemo:
    image: mxdevelopers/socioformadorapidemo:0.3
    ports:
      - "8081:80"
    environment:
     ASPNETCORE_URLS: http://+:80

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql5-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos